# Generated by Django 4.1.7 on 2023-02-25 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 13, 42, 54, 749813, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
    ]
